version: "3"

services:
  space-track:
    build: .
    restart: always
    ports:
      - "80:8080"
    volumes:
      - data:~/space-objects/db
    environment:
      - ST_USERNAME=
      - ST_PASSWORD=
